### ISSUE TITLE
Suggestions for small improvements

### ISSUE THREAD

**Issue by ivvv** [oliexdev/openScale#156]
After a week of using the app, a couple of suggestions:
 - exporting the table: currently the export file is  `/openScale_data_user.csv`. But I want to export the table to a different folder, e.g. one that I sync to the cloud. So, every time I have to manually add the folder name or to use a file manager to move the file from '/'. It would be more user friendly if the last user input (e.g. folder and filename) were  kept.
 - with my ageing eyes the blue, green and red limits for the parameters (weight, BMI etc) in the overview page are with such a tiny font that I cannot really tell those numbers. Is it possible to increase the font a little bit?

Thanks for the good work!

**Comment by oliexdev** [comment]
thanks for your enhancement ideas. I have implemented it with commit https://github.com/oliexdev/openScale/commit/09b306926890880a96a31704b3827b64c099c79f

Unfortunately, you are a little bit to late that this will be integrated into the openScale version 1.7 release because I have released the new openScale version recently.

Therefore, these minor changes will be officially integrated in the next release. In the meantime you can use the development version of openScale.
