### ISSUE TITLE
Feature request: Data points for absolute body fat

### ISSUE THREAD

**Issue by ghost** [oliexdev/openScale#255]
Hi, first off thanks for your efforts - i am not using closed source apps and i'm super happy this exists.

What would greatly improve my experience is a possibility to show absolute fat and fat-free mass w.r.t. the weight and body fat percentage measurements - not estimated values but just do (weight*percentage/100) and (weight - abs. fat).
So one would obtain this in the graph view:

![image](https://user-images.githubusercontent.com/26491995/39442671-5cdb6c90-4cb2-11e8-91ca-5c869fb3ee3e.png)

For me, these four metrics are the important ones because they show me how my body develops - in the example above i could see at first glance that i may be losing weight, but gaining muscle.

Also cool would be if i could enter the caliper measurements directly in the app and make it calculate the body fat percentage automatically. Right now i have to do it by hand or go on some website. I guess that would mean one more measurement to be enabled via toggle (plus a selection which calculation method should be used) and hard code the formulas (https://de.wikipedia.org/wiki/Calipometrie#Berechnungsmethoden).
I realize though that i might be the only who would use this, and the current way is fine too.

Thank you

**Comment by erijo** [comment]
You can change fat to use absolute values under settings -> measurements.

If I understand you correctly, what you would like to see added is an option to set lbm to weight minus fat. This could be added.

What is the kfa graph?

As for the caliper measurement I think it would be hard to add without it getting too complicated. Until we get more requests for it I'll think you'll have to do without in-app support.

**Comment by nightbluepn** [comment]
> You can change fat to use absolute values under settings -> measurements.

I didn't understand the measurement entries had a menu behind them  ...  ;)

Though i still think it should be possible to enter the body fat as a percentage and to then get the absolute fat as a derived metric (you would'nt even need to save it to the database).
If i switch to absolute body fat now, i would have to change all past values and make the calculation by hand in the future, all while not being able to view relative and absolute body fat at the same time.

> If I understand you correctly, what you would like to see added is an option to set lbm to weight minus fat. This could be added.

Yes, maybe add a menu to lbm where you can switch from estimated to derived (such as the one where you switch absolute/relative body fat).

> What is the kfa graph?
Sorry for the that, kfa is the german abbreviation for body fat percentage.

So my dream scenario would be to enter two measurements (body weight and body fat percentage) and then get the four metrics in the screenshot out of it.

By the way, since we just turned to may i noticed you can only show a month as a whole, maybe to show the last 30 days in month view can also be a good idea.

Regarding the caliper measurements: i understand, thats fine.

Thanks already for your answer!

**Comment by erijo** [comment]
Body fat is always stored as a percentage in the database. Toggling to absolute value will on change how it is input and presented. So your historic data will work just fine.

I don't know how to present body fat in both relative and absolute value without it becoming hard to understand for a casual user so for now I think you have to settle for one, unless you have a good idea.

**Comment by nightbluepn** [comment]
I haven't looked into the code, but maybe it's possible to switch the text from "Measurement in %" to "Input as %" and below that "Show as absolute" and "Show as %" as two seperate checkboxes which may both be checked.
I guess the current logic is a 1:1 relation between measurements and graph entries, so you would need a second fat measurement which is invisible in the menu but shows up in the graph view if the corresponding box is checked.

I reckon this wouldn't obstruct user experience (considering i didn't find this menu in the first place :smile: ).
Would this be very complex to do?

**Comment by nightbluepn** [comment]
So i installed the development version, exported the database, did an sql update on it to insert the LBM values retroactively and tried a new measurement -> works perfectly.
Thanks a lot for this.
