### ISSUE TITLE
Body fat evaluation range for females

### ISSUE THREAD

**Issue by Liesz** [oliexdev/openScale#403]
It might be that I didn't enter correctly the profile, as I'm new to the app. My profile has women marked but the colour ranges don't change. For non-athletes women, the normal range is fitness: 21-24% and normal: 25-30% (sources: https://academic.oup.com/ajcn/article/63/3/448S/4651512, https://en.wikipedia.org/wiki/Body_fat_percentage) so I would say that colouring red anything +23% and ending the scale at 30% is a bad idea, especially considering the high rate of body and self-image in women.

Again sorry if I did get it wrong, I searched through the issues here and found one that says that the 30% limit is fixed, but I just downloaded the app and it still shows it? Maybe it's because my % is below so it doesn't show? I downloaded from google play

Thank you for developing this and giving it great support!

**Comment by oliexdev** [comment]
The body fat is not ending by 30% the diagram is adjusted depending on your body fat (otherwise the diagram would unnecessary too big). Try it out, enter some high body fat value for example 60%. 

The normal ranges depends on your age and your sex. 

```
        fatEvaluateSheet_Woman.add(new sheetEntry(10, 14, 16, 21));
        fatEvaluateSheet_Woman.add(new sheetEntry(15, 19, 17, 22));
        fatEvaluateSheet_Woman.add(new sheetEntry(20, 29, 18, 23));
        fatEvaluateSheet_Woman.add(new sheetEntry(30, 39, 19, 24));
        fatEvaluateSheet_Woman.add(new sheetEntry(40, 49, 20, 25));
        fatEvaluateSheet_Woman.add(new sheetEntry(50, 59, 21, 26));
        fatEvaluateSheet_Woman.add(new sheetEntry(60, 69, 22, 27));
        fatEvaluateSheet_Woman.add(new sheetEntry(70, 1000, 23, 28));
```

_Note: first number is the lower age; second number is the maximal age, third number is the normal range min body fat; fourth number is the normal range max body fat_

There are so many different recommendations for the normal range for women and men. Your reference is for example 20 years old but if you google for it, you will find at least 5 different range tables for men and women! If you have a good quality and scientific publication feel free to give a link.
