### ISSUE TITLE
add Changelog

### ISSUE THREAD

**Issue by sciamano** [oliexdev/openScale#41]
please add a changelog and link it to F-Droid' metadata. That way the users can easily see the difference between the installed version and the proposed update. It's important for people who really care about the software on their phone and what changes from the app to expect. Right now one has to find and examine all the commit messages to get a picture of what is going on...

**Comment by oliexdev** [comment]
under [openScale releases](https://github.com/oliexdev/openScale/releases) you find a short description what has changed and if you want further details you can see all commits since the last release easily. 
I don't want to maintain another change log, maybe F-Droid should use the github release note.
