### ISSUE TITLE
Missing measurements behavior

### ISSUE THREAD

**Issue by maciej-galuszewski** [oliexdev/openScale#468]
There are situations when you can't input all measurements (for example because you are away from home and can use scale which displays weight only).

In such cases I am forced to put "0" in each missing measurements, because fields are required. This results in incorrect calculation of weekly/monthly averages and looks ugly in graphs (measurements are treated as if they were actually "0").

Proposed solution: ideally application should allow to leave some measurements empty, but I assume it would have a lot of impact on application. Alternatively application could exclude "0" measurements from averages and graphs, but I'm not sure it should work like that for each type of measurement (please note that I have tested it for muscle and fat measurements only).

**Comment by oliexdev** [comment]
you can disable/enable certain measurements completely to adjust you needs in the settings, so you don't have to input some measurements.
You shouldn't set a missing measurements a better solution is to set the previous measurement, normally you don't have huge changes since last your measurement. That's why openScale will pre set you last measurement in the add dialog.
But with commit https://github.com/oliexdev/openScale/commit/0c93b8888e1d0fab95f4aa508c7b9878df4f00ba I don't display zero values anymore in the graph but be aware the average is still calculate with the zero value.
You can try out the latest dev version.
