### ISSUE TITLE
Daily reminder

### ISSUE THREAD

**Issue by wolkenschieber** [oliexdev/openScale#5]
The app looks great and fulfills its task quite perfectly. But I'm having trouble doing continuous measurements. There a configurable daily reminder through notification would be a real enhancement for me.

**Comment by oliexdev** [comment]
Hi wolkenschieber

thank you for your suggestion. If I have a bit more time I will implement in the next version an option to enable/disable a customizable notification. I give a quick look to search for information how to implement this on Android. There is a good developer page under https://developer.android.com/training/scheduling/alarms.html
If you are a developer yourself, I would be happy if you can create a pull request with a first implementation.
Anyhow which text should be displayed in the notification message?

Best regards
Oli

**Comment by wolkenschieber** [comment]
Time is also rare for me, but if I find some I'll give it a go.

> Anyhow which text should be displayed in the notification message?

I'd go with:
*Daily reminder*
*Tab to enter weight*

**Comment by oliexdev** [comment]
I implemented a first weight reminder version, see commit https://github.com/oliexdev/openScale/commit/6eeb5f962f7187d6b55464978d89b5ebf4d27fbd
I made the notification text editable (default text is "Time to weight").
But this version need to be tested. Currently I am not sure if there is still a bug because it was more complicated as I first thought. Maybe somebody can review it.

**Comment by oliexdev** [comment]
I think I found a bug, see commit https://github.com/oliexdev/openScale/commit/1645ce4e989d0f88c690a03a0fc36945a0bed1a3
