### ISSUE TITLE
[Feature request] Make app wait for bt connection, so user can straight step to scale with both legs.

### ISSUE THREAD

**Issue by huuhaa** [oliexdev/openScale#598]
**Is your feature request related to a problem? Please describe.**
It's bit frustrating when scales nowdays supports function to measure weight, musclemass etc. by straight at jumping on the scale with both legs without first stepping on scale at one leg to turn it on. OpenScale forces me to use the scale "oldfashion" way to first step on it with one leg to "start" scale (while app is open) so app can connect to BT before stepping on scale with both legs and letting scale do measurements. 
 
**Describe the solution you'd like**
I would like to use scale with openScale like I do with official app, by opening app and leaving it open while stepping to scale with both legs and let it do measurements. Currently if trying this method values won't be tranferred to openScale app.

**Describe alternatives you've considered**
I have tried to change from settings => Bluetooth to "Connect to scale at startup" on and off, but only "on" allows to transfer any values at openScale app at all, so obviously neiher option allows me to use scale like described at solution I would like.

**Additional context**
I'm using app with Xiaomi Mi Scale 2

**Comment by oliexdev** [comment]
Every scale is different, since you are using Xiaomi Mi Scale 2 it is more easier than you have described. You don't have to open the openScale app while your are measuring. If you are done or even on another day just open openScale and sync to the scale. openScale will fetch the last history measurements.
What you see in the official app is the advertisement measuring which openScale don't fetch because this is not necessary.
