### ISSUE TITLE
support for iOS?

### ISSUE THREAD

**Issue by Richter-Ko** [oliexdev/openScale#694]
is it possible to work it on iOS?

**Comment by oliexdev** [comment]
no because it's an Android app

**Comment by akirataguchi115** [comment]
I just found this issue while searching for iOS support. Any possibility to re-open this issue?

I am fustrated how the iOS Health Coach app has stopped communicating my scale data to my iPhone.

I would want a iOS version of this app because @MartinNowack seems to have implemented support for SBF 70 which I have.

I've considered just getting rid of the scale due to the aforementioned lack of support on iOS.

**Comment by oliexdev** [comment]
sorry to support iOS you have to rewrite the whole app which I definitely not have the time for.

**Comment by akirataguchi115** [comment]
Maybe if this issue was open someone could rewrite it in some framework that is multiplaform?
